# Generated by Django 4.0.5 on 2022-09-02 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_One',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Todays_Deals', 'Todays_Deals'), ('Recommended', 'Recommended'), ('Similar', 'Similar')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category_Two',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Health_Beauty', 'Health_Beauty'), ('Kitchen_Appliances', 'Kitchen_Appliances'), ('Phone_Tablets', 'Phone_Tablets'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Garden_Outdoors', 'Garden_Outdoors'), ('Furniture', 'Furniture')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='similar_products',
            name='user',
        ),
        migrations.RemoveField(
            model_name='today_deals',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='recommended_products',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='similar_products',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='today_deals',
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='products',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Recommended_Products',
        ),
        migrations.DeleteModel(
            name='Similar_Products',
        ),
        migrations.DeleteModel(
            name='Today_Deals',
        ),
        migrations.AddField(
            model_name='products',
            name='category_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category_one'),
        ),
        migrations.AddField(
            model_name='products',
            name='category_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category_two'),
        ),
    ]
