# Generated by Django 4.0.5 on 2022-09-05 06:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='product_image'),
        ),
    ]
