# Generated by Django 4.0.5 on 2022-09-05 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_products_profile_pic_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='user',
        ),
    ]
